# Generated by Django 6.0.3 on 2026-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_photoproduct_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='preview_image',
            field=models.ImageField(upload_to='products/previews/'),
        ),
    ]
